services:
  bank.core.api:
    image: ${DOCKER_REGISTRY-}bankcoreapi
    build:
      context: .
      dockerfile: src/core/Bank.Core.Api/Dockerfile
    depends_on:
      - postgres
    networks:
      - my-net
    ports:
      - "5001:8080"

  bank.credits.api:
    image: ${DOCKER_REGISTRY-}bankcreditsapi
    build:
      context: .
      dockerfile: src/credits/Bank.Credits.Api/Dockerfile
    depends_on:
      - postgres
    networks:
      - my-net
    ports:
      - "5002:8080"

  bank.users.api:
    image: ${DOCKER_REGISTRY-}bankusersapi
    build:
      context: .
      dockerfile: src/users/Bank.Users.Api/Dockerfile
    depends_on:
      - postgres
      - redis  
    networks:
      - my-net
    ports:
      - "5003:8080"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4123
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    networks:
      - my-net
    ports:
      - "6379:6379"
  
networks:
  my-net:
    driver: bridge
     