version: "3.5"

x-common: &common
  networks:
    - my-net
  environment:
    RUNTIME_ENVIRONMENT: "Docker"

services:
  bank.core.api:
    image: ${DOCKER_REGISTRY-}bankcoreapi
    build:
      context: .
      dockerfile: src/core/Bank.Core.Api/Dockerfile
    depends_on:
      - postgres
    <<: *common
    ports:
      - "5001:8080"

  bank.credits.api:
    image: ${DOCKER_REGISTRY-}bankcreditsapi
    build:
      context: .
      dockerfile: src/credits/Bank.Credits.Api/Dockerfile
    depends_on:
      - bank.users.api
      - postgres
    <<: *common
    ports:
      - "5002:8080"

  bank.users.api:
    image: ${DOCKER_REGISTRY-}bankusersapi
    build:
      context: .
      dockerfile: src/users/Bank.Users.Api/Dockerfile
    depends_on:
      - postgres
      - redis
    <<: *common
    ports:
      - "5003:8080"

  bank.users.authweb:
    image: ${DOCKER_REGISTRY-}bankusersauthweb
    build:
      context: .
      dockerfile: src/users/Bank.Users.AuthWeb/Dockerfile
    depends_on:
      - bank.users.api
      - postgres
      - redis
    <<: *common
    ports:
      - "5004:8080"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - my-net
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    networks:
      - my-net
    ports:
      - "6379:6379"

networks:
  my-net:
    driver: bridge
